spring:
  application:
    name: item-service
  kafka:
    bootstrap-servers: 127.0.0.1:9092

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/item-db
    username: sa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        use_sql_comments: false
        format_sql: true
  sql:
    init:
      mode: always
  jackson:
    default-property-inclusion: non_null
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health