version : '3.9'
services :

# ----------- SERVER ------------
  eureka-server:
    build:
      context: ./eureka-service
      dockerfile: Dockerfile
    restart: always
    networks:
      - shop-network
    ports:
      - '8761:8761'
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 40s

# ------------ REDIS ------------
  redis-lock:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    networks:
      - shop-network
  redis-item-price-cache:
    image: redis:latest
    restart: always
    ports:
      - '6380:6379'
    networks:
      - shop-network
  redis-time-deal:
    image: redis:latest
    restart: always
    ports:
      - '6381:6379'
    networks:
      - shop-network


# ------------ KAFKA ------------
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - shop-network
  kafka-service:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
#      KAFKA_ADVERTISED_HOST_NAME: kafka-service
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      AUTO_CREATE_TOPICS: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - shop-network
    depends_on:
      - zookeeper
networks:
  shop-network:
    driver: bridge