version : '3.9'
services :

# ------------ MySQL ------------
  redis-lock:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    networks:
      - shop-mysql-network

networks:
  shop-mysql-network:
    driver: bridge