version : '3.9'
services :

# ------------ MySQL ------------
  redis-lock:
    command: 'redis-server --requirepass mypassword --port 6379'
    image: redis:latest
    restart: always
    ports:
      - '6381:6379'
    networks:
      - shop-mysql-network

networks:
  shop-mysql-network:
    driver: bridge