server:
  port: 8000

eureka:
  client:
    registry-fetch-interval-seconds: 10
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL}
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalLoggingFilter
          args:
            preLogger: true
            postLogger: true
      routes:
        - id: not-allowed-item-path
          uri: no://op
          predicates:
            - Path=/item/*/price
            - Method=*
          filters:
            - SetStatus=404
        - id: item-service-api
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/item,/item/**
            - Method=GET
          filters:
            - RewritePath=/item/(?<segment>.*), /$\{segment}
        - id: stock-service-api
          uri: lb://STOCK-SERVICE
          predicates:
            - Path=/stock/**
            - Method=GET
          filters:
            - RewritePath=/stock/(?<segment>.*), /$\{segment}
