spring:
  application:
    name: stock-service
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_URL}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${STOCK_DB_URL}
    username: ${STOCK_DB_USERNAME}
    password: ${STOCK_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        use_sql_comments: false
        format_sql: false
  sql:
    init:
      mode: always
redis:
  lock:
    host: ${REDIS_LOCK_HOST}
    port: ${REDIS_LOCK_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL}
    fetch-registry: true
    register-with-eureka: true
management:
  endpoints:
    web:
      exposure:
        include: health
