spring:
  application:
    name: stock-service

redis:
  lock:
    host: localhost
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: true
management:
  endpoints:
    web:
      exposure:
        include: health
