spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: 127.0.0.1:9092

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/order-db
    username: sa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        use_sql_comments: false
        format_sql: false
  sql:
    init:
      mode: always


redis:
  lock:
    host: localhost
    port: 6379
  price:
    host: localhost
    port: 6380
  time-deal:
    host: localhost
    port: 6381
  stock:
    host: localhost
    port: 6382

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health
server:
  port: 8082