server:
  port: 0

spring:
  application:
    name: order-service

redis:
  lock:
    host: localhost
    port: 6379
  price:
    host: localhost
    port: 6380

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: true
